/**
 * Golden model tests — the whole pipeline, from raw upstream bytes to scored
 * model, replayed offline.
 *
 * What this is for: `finance.js` has never had a test. Model assembly
 * (`buildModel`, `buildHistory`, `buildPeHistory`, `toRecord`) is roughly 450
 * lines that are about to move into `core/`, and moving untested code is how a
 * refactor quietly changes a number. This pins the current output first, so
 * the move can be proved to have changed nothing.
 *
 * It is a characterisation test, not a correctness test. The snapshots were
 * generated by the code they now guard, so they cannot show that today's
 * numbers are *right* — `scoring.test.js` is what argues for that. What they
 * show is that tomorrow's numbers are *the same*. The assertions in §2 below
 * carry the independent claims, so a snapshot that is wrong in an obvious way
 * still fails.
 *
 * Doc 13 §10 specifies the same fixtures run through QuickJS on Android and
 * diffed against these files. That is the parity gate; this is half of it.
 *
 * Re-record with:  node scripts/record-fixture.mjs NOK AAPL JPM
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'fs';
import os from 'os';
import path from 'path';

import {
  loadFixture,
  installReplayFetch,
  fixturePath,
  normaliseModel
} from '../tools/fixture-http.js';

// DATA_DIR is resolved when db.js loads, so it has to be set before the import.
const scratch = fs.mkdtempSync(path.join(os.tmpdir(), 'omaha-golden-'));
process.env.DATA_DIR = scratch;

const { initDatabase, db } = await import('../server/db.js');
const { getStockData } = await import('../server/finance.js');
const { __resetSession } = await import('../core/providers/yahoo.js');

initDatabase();

const TICKERS = ['NOK', 'AAPL', 'JPM'];

/** Run one ticker against its recorded upstream responses. */
async function scoreFromFixture(ticker) {
  __resetSession();
  const restore = installReplayFetch(loadFixture(ticker));
  try {
    // Forced: the point is to exercise ingestion and assembly, not the cache.
    return await getStockData(ticker, true);
  } finally {
    restore();
  }
}

// -------------------------------------------------- 1. the snapshots

for (const ticker of TICKERS) {
  test(`${ticker} produces the recorded model, field for field`, async () => {
    const model = await scoreFromFixture(ticker);
    assert.ok(model, `${ticker} produced no model`);

    const expected = JSON.parse(fs.readFileSync(fixturePath(ticker, 'model'), 'utf8'));
    assert.deepEqual(
      normaliseModel(model),
      expected,
      `${ticker} model differs from the recorded snapshot. If the change was ` +
      'intended, re-record and review the diff as part of the change.'
    );
  });
}

// -------------------------------------------------- 2. independent claims
//
// These do not depend on the snapshots. They state what these three tickers
// were chosen to demonstrate, so a snapshot regenerated around a defect still
// fails here.

test('a bank reports Altman Z as inapplicable rather than computing one', async () => {
  const jpm = await scoreFromFixture('JPM');

  assert.equal(jpm.sector, 'Financial Services');
  assert.equal(
    jpm.altman_z,
    null,
    'Altman Z is undefined for a lender; a number here would be fabricated'
  );

  const na = jpm.checklist.filter((c) => c.status === 'na');
  assert.ok(
    na.length >= 4,
    `expected several checks to be inapplicable to a bank, saw ${na.length}`
  );
  assert.ok(
    jpm.health_score !== null,
    'inapplicable checks are excluded from the score, not fatal to it'
  );
});

test('a depositary receipt keeps trading and reporting currencies apart', async () => {
  const nok = await scoreFromFixture('NOK');
  const metrics = nok.summary?.metrics || {};

  assert.equal(nok.currency, 'USD', 'NOK trades in USD');
  assert.equal(
    metrics.reportingCurrency ?? nok.summary?.readMeFirst?.reportingCurrency,
    'EUR',
    'NOK reports in EUR; conflating the two divides USD market cap by EUR debt'
  );
});

test('an industrial with full coverage scores on every sub-score', async () => {
  const aapl = await scoreFromFixture('AAPL');

  assert.equal(aapl.checklist.filter((c) => c.status === 'na').length, 0);
  assert.ok(typeof aapl.altman_z === 'number' && aapl.altman_z > 0);
  assert.ok(
    aapl.summary?.metrics?.fiscalPeriodEnd?.endsWith('-09-30'),
    'AAPL files on a September year end — the model must not assume December'
  );
});

test('an unrecorded call fails loudly rather than reaching upstream', async () => {
  // Guards the guard: if installReplayFetch stopped intercepting, the suite
  // would silently start testing live Yahoo and pass for the wrong reason.
  // Uses a ticker with no cache row, so there is no stale copy to fall back to
  // and the failure has to surface.
  const restore = installReplayFetch({});
  try {
    await assert.rejects(
      () => getStockData('ZZZZ', true),
      /No fixture for/,
      'an unrecorded call must fail loudly rather than reach upstream'
    );
  } finally {
    restore();
  }
});

test('a cached ticker degrades to stale data instead of failing', async () => {
  // NOK is in the cache by now, from the snapshot test above. With the
  // upstream unreachable it must serve that copy, marked stale and labelled
  // with the reason — the behaviour the alert sweep reads to decide to stop.
  const restore = installReplayFetch({});
  try {
    const model = await getStockData('NOK', true);
    assert.ok(model, 'a cached ticker must still return something');
    assert.equal(model.stale, true);
    assert.equal(model.staleReason, 'network');
    assert.equal(model.ticker, 'NOK');
    assert.ok(model.health_score !== undefined, 'the cached score is still served');
  } finally {
    restore();
  }
});

test.after(() => {
  try {
    db.close();
  } catch {
    // already closed
  }
  try {
    fs.rmSync(scratch, { recursive: true, force: true });
  } catch {
    // Windows holds WAL files open briefly; a temp dir left behind is harmless
  }
});
